/**
 * ============================================================
 * AGENT 3 — AUTOMATION SCRIPT GENERATOR AGENT
 * ============================================================
 * Purpose : Convert approved manual test cases into Playwright
 *           automation scripts following Page Object Model.
 *
 * Inputs  : manual-test-cases/TC_<MODULE>.md
 *           docs/pages/<MODULE>.md
 *
 * Outputs : automation/pages/<module>.page.ts  (if not exists)
 *           automation/tests/<module>.spec.ts  (if not exists)
 *
 * Rules:
 *   - Each test must correspond to a Steps to Reproduce from TC
 *   - Never overwrite existing automation files
 *   - Use stable Playwright locators (no hardcoded waits)
 *   - Map each test to its TC_ID in comments
 *
 * Run:
 *   npx ts-node agents/agent3-automation-gen.ts <MODULE_NAME>
 *
 *   Example:
 *   npx ts-node agents/agent3-automation-gen.ts Customers
 * ============================================================
 */

import * as fs from 'fs';
import * as path from 'path';

const MODULE = process.argv[2];

const PAGES_DIR = path.join(process.cwd(), 'automation', 'pages');
const TESTS_DIR = path.join(process.cwd(), 'automation', 'tests');

function fileExists(filePath: string): boolean {
  return fs.existsSync(filePath);
}

function generatePageObject(moduleName: string): void {
  const fileName = `${moduleName.toLowerCase()}.page.ts`;
  const filePath = path.join(PAGES_DIR, fileName);

  if (fileExists(filePath)) {
    console.log(`   ⚠️  Page Object already exists, skipping: ${filePath}`);
    console.log(`      (Agent 3 never overwrites existing files per GLOBAL_RULE_3)`);
    return;
  }

  const content = `/**
 * PAGE OBJECT — ${moduleName}
 * Generated by Agent 3 — Automation Script Generator
 * 
 * ⚠️ DO NOT EDIT SELECTORS DIRECTLY.
 * If a selector breaks, use Agent 6 (Script Healing Agent) for recommendations.
 */
import { Page, Locator, expect } from '@playwright/test';

export class ${moduleName}Page {
  readonly page: Page;

  // ── Add your locators here based on docs/pages/${moduleName.toUpperCase()}.md ──

  constructor(page: Page) {
    this.page = page;
  }

  async navigate(): Promise<void> {
    await this.page.goto('https://uat-web.xrportal.in/admin/${moduleName.toLowerCase()}');
    console.log('✅ Navigated to ${moduleName} page');
  }

  async screenshot(label: string): Promise<void> {
    const ts = Date.now();
    await this.page.screenshot({ path: \`reports/screenshots/${moduleName.toLowerCase()}_\${label}_\${ts}.png\` });
  }
}
`;
  fs.writeFileSync(filePath, content);
  console.log(`   ✅ Page Object created: ${filePath}`);
}

function generateSpecFile(moduleName: string): void {
  const fileName = `${moduleName.toLowerCase()}.spec.ts`;
  const filePath = path.join(TESTS_DIR, fileName);

  if (fileExists(filePath)) {
    console.log(`   ⚠️  Spec file already exists, skipping: ${filePath}`);
    console.log(`      (Agent 3 never overwrites existing files per GLOBAL_RULE_3)`);
    return;
  }

  const content = `/**
 * TEST SUITE — ${moduleName}
 * Generated by Agent 3 — Automation Script Generator
 *
 * Maps to: manual-test-cases/TC_${moduleName.toUpperCase()}.md
 * Page Object: automation/pages/${moduleName.toLowerCase()}.page.ts
 * 
 * Run:
 *   npx playwright test ${moduleName.toLowerCase()}.spec.ts --project=regression --headed --workers=1
 */

import { test, expect } from '@playwright/test';
import { ${moduleName}Page } from '../pages/${moduleName.toLowerCase()}.page';
import path from 'path';

test.use({
  storageState: path.join(__dirname, '../fixtures/.auth/admin.json'),
});

test.describe('${moduleName} Module Tests', () => {

  test.beforeEach(async ({ page }) => {
    const module = new ${moduleName}Page(page);
    await module.navigate();
  });

  // ── Add test cases below, mapping each to its TC_ID ──────────────────

  // TODO: TC_${moduleName.toUpperCase()}_001 — Add first test case here

});
`;

  fs.writeFileSync(filePath, content);
  console.log(`   ✅ Spec file created: ${filePath}`);
}

function run() {
  console.log('⚙️  [Agent 3] AUTOMATION SCRIPT GENERATOR starting...\n');

  if (!MODULE) {
    console.log('Usage: npx ts-node agents/agent3-automation-gen.ts <ModuleName>');
    console.log('Example: npx ts-node agents/agent3-automation-gen.ts Towers');
    process.exit(1);
  }

  console.log(`📂 Generating automation for module: ${MODULE}`);
  generatePageObject(MODULE);
  generateSpecFile(MODULE);

  console.log(`\n✅ [Agent 3] AUTOMATION GENERATION COMPLETE for: ${MODULE}`);
  console.log(`   Next step → Update the generated files with real locators and test steps.`);
  console.log(`   Then run Agent 4 to execute tests.`);
}

run();
