'use strict';

// tests/api/kyc-assistance.api.spec.js
// CP Portal — KYC Assistance API specs (STUB)
//
// No API TCs in current TestCases.md batch (2026-06-07 APPROVED).
// FRD §1.7 marks PAN format validation as server-side, but no API-type TCs
// were generated by BA Agent in this batch. The Submit-disabled gating pattern
// means the client never invokes POST /api/v1/cp/registration unless the form
// is fully valid client-side first.
//
// Add tests here when API contract TCs are defined for endpoints:
//   - POST /api/v1/cp/registration  (CP self-KYC submission)
//   - GET  /api/v1/cp/kyc/status    (KYC review status — TBD per FRD)

const { test } = require('@playwright/test');

test.describe('KYC Assistance API — Channel Partner Portal', () => {
  test.fixme('TC_CPKYC_API_PLACEHOLDER — pending API contract TCs', async () => {
    // No API TCs in current TestCases.md batch. Add when API contract TCs are defined.
  });
});
