'use strict';

/**
 * JbpSubmissionPage.js — Scaffolded Page Object Model for channel-partner / jbp-submission.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/channel-partner/locator-map.json (module key: "jbp-submission").
 *
 * Element count at scaffold time: 9
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/channel-partner/locator-map.json');

const L = locatorMap['jbp-submission'] || {};

const JBPSUBMISSION_URL = 'https://uat-web.xrportal.in/jbp';

class JbpSubmissionPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = JBPSUBMISSION_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.logoutButton                   = page.locator(L['logoutButton'] && L['logoutButton'].selector);
    this.homeLink                       = page.locator(L['homeLink'] && L['homeLink'].selector);
    this.kYCLink                        = page.locator(L['kYCLink'] && L['kYCLink'].selector);
    this.jBPLink                        = page.locator(L['jBPLink'] && L['jBPLink'].selector);
    this.leadsLink                      = page.locator(L['leadsLink'] && L['leadsLink'].selector);
    this.rcTabs0Tab1                    = page.locator(L['rcTabs0Tab1'] && L['rcTabs0Tab1'].selector);
    this.rcTabs0Tab2                    = page.locator(L['rcTabs0Tab2'] && L['rcTabs0Tab2'].selector);
    this.rcTabs0Tab3                    = page.locator(L['rcTabs0Tab3'] && L['rcTabs0Tab3'].selector);
    this.jBPDashboardHeading            = page.locator(L['jBPDashboardHeading'] && L['jBPDashboardHeading'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { JbpSubmissionPage };
