'use strict';

/**
 * KycAssistancePage.js — Scaffolded Page Object Model for channel-partner / kyc-assistance.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/channel-partner/locator-map.json (module key: "kyc-assistance").
 *
 * Element count at scaffold time: 17
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/channel-partner/locator-map.json');

const L = locatorMap['kyc-assistance'] || {};

const KYCASSISTANCE_URL = 'https://uat-web.xrportal.in/kyc';

class KycAssistancePage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = KYCASSISTANCE_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.logoutButton                   = page.locator(L['logoutButton'] && L['logoutButton'].selector);
    this.cancelButton                   = page.locator(L['cancelButton'] && L['cancelButton'].selector);
    this.submitButton                   = page.locator(L['submitButton'] && L['submitButton'].selector);
    this.homeLink                       = page.locator(L['homeLink'] && L['homeLink'].selector);
    this.kYCLink                        = page.locator(L['kYCLink'] && L['kYCLink'].selector);
    this.jBPLink                        = page.locator(L['jBPLink'] && L['jBPLink'].selector);
    this.leadsLink                      = page.locator(L['leadsLink'] && L['leadsLink'].selector);
    this.enterNameInput                 = page.locator(L['enterNameInput'] && L['enterNameInput'].selector);
    this.enterFullAddressInput          = page.locator(L['enterFullAddressInput'] && L['enterFullAddressInput'].selector);
    this.rcSelect0                      = page.locator(L['rcSelect0'] && L['rcSelect0'].selector);
    this.enterNameInput2                = page.locator(L['enterNameInput2'] && L['enterNameInput2'].selector);
    this.enterEmailIDInput              = page.locator(L['enterEmailIDInput'] && L['enterEmailIDInput'].selector);
    this.enterMobileNumberInput         = page.locator(L['enterMobileNumberInput'] && L['enterMobileNumberInput'].selector);
    this.enterPinCodeInput              = page.locator(L['enterPinCodeInput'] && L['enterPinCodeInput'].selector);
    this.enterPANNumberInput            = page.locator(L['enterPANNumberInput'] && L['enterPANNumberInput'].selector);
    this.enterRERANumberInput           = page.locator(L['enterRERANumberInput'] && L['enterRERANumberInput'].selector);
    this.kYCHeading                     = page.locator(L['kYCHeading'] && L['kYCHeading'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { KycAssistancePage };
