'use strict';

/**
 * LeadsManagementPage.js — Scaffolded Page Object Model for channel-partner / leads-management.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/channel-partner/locator-map.json (module key: "leads-management").
 *
 * Element count at scaffold time: 16
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/channel-partner/locator-map.json');

const L = locatorMap['leads-management'] || {};

const LEADSMANAGEMENT_URL = 'https://uat-web.xrportal.in/leads';

class LeadsManagementPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = LEADSMANAGEMENT_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.logoutButton                   = page.locator(L['logoutButton'] && L['logoutButton'].selector);
    this.resendNotificationButton       = page.locator(L['resendNotificationButton'] && L['resendNotificationButton'].selector);
    this.copyLinkButton                 = page.locator(L['copyLinkButton'] && L['copyLinkButton'].selector);
    this.resendNotificationButton2      = page.locator(L['resendNotificationButton2'] && L['resendNotificationButton2'].selector);
    this.copyLinkButton2                = page.locator(L['copyLinkButton2'] && L['copyLinkButton2'].selector);
    this.resendNotificationButton3      = page.locator(L['resendNotificationButton3'] && L['resendNotificationButton3'].selector);
    this.copyLinkButton3                = page.locator(L['copyLinkButton3'] && L['copyLinkButton3'].selector);
    this.homeLink                       = page.locator(L['homeLink'] && L['homeLink'].selector);
    this.kYCLink                        = page.locator(L['kYCLink'] && L['kYCLink'].selector);
    this.jBPLink                        = page.locator(L['jBPLink'] && L['jBPLink'].selector);
    this.leadsLink                      = page.locator(L['leadsLink'] && L['leadsLink'].selector);
    this.rcSelect1                      = page.locator(L['rcSelect1'] && L['rcSelect1'].selector);
    this.rcSelect0                      = page.locator(L['rcSelect0'] && L['rcSelect0'].selector);
    this.searchCustomerInput            = page.locator(L['searchCustomerInput'] && L['searchCustomerInput'].selector);
    this.rcSelect2                      = page.locator(L['rcSelect2'] && L['rcSelect2'].selector);
    this.leadsHeading                   = page.locator(L['leadsHeading'] && L['leadsHeading'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { LeadsManagementPage };
