'use strict';

/**
 * LoginPage.js — Scaffolded Page Object Model for channel-partner / login.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/channel-partner/locator-map.json (module key: "login").
 *
 * Element count at scaffold time: 5
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/channel-partner/locator-map.json');

const L = locatorMap['login'] || {};

const LOGIN_URL = 'https://uat-web.xrportal.in/login';

class LoginPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = LOGIN_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.sendOTPButton                  = page.locator(L['sendOTPButton'] && L['sendOTPButton'].selector);
    this.termsConditionsLink            = page.locator(L['termsConditionsLink'] && L['termsConditionsLink'].selector);
    this.privacyPolicyLink              = page.locator(L['privacyPolicyLink'] && L['privacyPolicyLink'].selector);
    this.enterMobileNumberInput         = page.locator(L['enterMobileNumberInput'] && L['enterMobileNumberInput'].selector);
    this.gROWTHPARTNERLOGINHeading      = page.locator(L['gROWTHPARTNERLOGINHeading'] && L['gROWTHPARTNERLOGINHeading'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { LoginPage };
