'use strict';

/**
 * ProjectInformationPage.js — Scaffolded Page Object Model for channel-partner / project-information.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/channel-partner/locator-map.json (module key: "project-information").
 *
 * Element count at scaffold time: 19
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/channel-partner/locator-map.json');

const L = locatorMap['project-information'] || {};

const PROJECTINFORMATION_URL = 'https://uat-web.xrportal.in/project1';

class ProjectInformationPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = PROJECTINFORMATION_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.logoutButton                   = page.locator(L['logoutButton'] && L['logoutButton'].selector);
    this.copyLinkButton                 = page.locator(L['copyLinkButton'] && L['copyLinkButton'].selector);
    this.downloadQRCodeButton           = page.locator(L['downloadQRCodeButton'] && L['downloadQRCodeButton'].selector);
    this.createLeadButton               = page.locator(L['createLeadButton'] && L['createLeadButton'].selector);
    this.resetBtn                       = page.locator(L['resetBtn'] && L['resetBtn'].selector);
    this.resetBtn2                      = page.locator(L['resetBtn2'] && L['resetBtn2'].selector);
    this.resetBtn3                      = page.locator(L['resetBtn3'] && L['resetBtn3'].selector);
    this.homeLink                       = page.locator(L['homeLink'] && L['homeLink'].selector);
    this.kYCLink                        = page.locator(L['kYCLink'] && L['kYCLink'].selector);
    this.jBPLink                        = page.locator(L['jBPLink'] && L['jBPLink'].selector);
    this.leadsLink                      = page.locator(L['leadsLink'] && L['leadsLink'].selector);
    this.riInput                        = page.locator(L['riInput'] && L['riInput'].selector);
    this.riInput2                       = page.locator(L['riInput2'] && L['riInput2'].selector);
    this.enterMobileNumberInput         = page.locator(L['enterMobileNumberInput'] && L['enterMobileNumberInput'].selector);
    this.rcSelect0                      = page.locator(L['rcSelect0'] && L['rcSelect0'].selector);
    this.searchCustomerInput            = page.locator(L['searchCustomerInput'] && L['searchCustomerInput'].selector);
    this.rcSelect1                      = page.locator(L['rcSelect1'] && L['rcSelect1'].selector);
    this.welcomeGPTestNameHeading       = page.locator(L['welcomeGPTestNameHeading'] && L['welcomeGPTestNameHeading'].selector);
    this.customersHeading               = page.locator(L['customersHeading'] && L['customersHeading'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { ProjectInformationPage };
