'use strict';

/**
 * AllocationExperiencePage.js — Scaffolded Page Object Model for buyer / allocation-experience.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/buyer/locator-map.json (module key: "allocation-experience").
 *
 * Element count at scaffold time: 2
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/buyer/locator-map.json');

const L = locatorMap['allocation-experience'] || {};

const ALLOCATIONEXPERIENCE_URL = 'https://uat.xrportal.in/allotment';

class AllocationExperiencePage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = ALLOCATIONEXPERIENCE_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.el404Heading                   = page.locator(L['404Heading'] && L['404Heading'].selector);
    this.thisPageCouldNotBeFoundHeading = page.locator(L['thisPageCouldNotBeFoundHeading'] && L['thisPageCouldNotBeFoundHeading'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { AllocationExperiencePage };
