'use strict';

/**
 * HomeLoanPage.js — Scaffolded Page Object Model for buyer / home-loan.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/buyer/locator-map.json (module key: "home-loan").
 *
 * Element count at scaffold time: 9
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/buyer/locator-map.json');

const L = locatorMap['home-loan'] || {};

const HOMELOAN_URL = 'https://uat.xrportal.in/homeloan';

class HomeLoanPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = HOMELOAN_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.previousSlide                  = page.locator(L['previousSlide'] && L['previousSlide'].selector);
    this.nextSlide                      = page.locator(L['nextSlide'] && L['nextSlide'].selector);
    this.sendOTPButton                  = page.locator(L['sendOTPButton'] && L['sendOTPButton'].selector);
    this.termsConditionsLink            = page.locator(L['termsConditionsLink'] && L['termsConditionsLink'].selector);
    this.privacyPolicyLink              = page.locator(L['privacyPolicyLink'] && L['privacyPolicyLink'].selector);
    this.enterMobileNumberInput         = page.locator(L['enterMobileNumberInput'] && L['enterMobileNumberInput'].selector);
    this.rcTabs0Tab1                    = page.locator(L['rcTabs0Tab1'] && L['rcTabs0Tab1'].selector);
    this.rcTabs0Tab2                    = page.locator(L['rcTabs0Tab2'] && L['rcTabs0Tab2'].selector);
    this.aPPLICANTLOGINHeading          = page.locator(L['aPPLICANTLOGINHeading'] && L['aPPLICANTLOGINHeading'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { HomeLoanPage };
