'use strict';

/**
 * PaymentSchedulePage.js — Scaffolded Page Object Model for buyer / payment-schedule.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/buyer/locator-map.json (module key: "payment-schedule").
 *
 * Element count at scaffold time: 2
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/buyer/locator-map.json');

const L = locatorMap['payment-schedule'] || {};

const PAYMENTSCHEDULE_URL = 'https://uat.xrportal.in/payment-schedule';

class PaymentSchedulePage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = PAYMENTSCHEDULE_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.el404Heading                   = page.locator(L['404Heading'] && L['404Heading'].selector);
    this.thisPageCouldNotBeFoundHeading = page.locator(L['thisPageCouldNotBeFoundHeading'] && L['thisPageCouldNotBeFoundHeading'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { PaymentSchedulePage };
