/**
 * ============================================================
 * AGENT 4 — TEST EXECUTION AGENT
 * ============================================================
 * Purpose : Execute Playwright tests and record results.
 *
 * Responsibilities:
 *   - Run all or specific module test suites
 *   - Capture screenshots and traces automatically
 *   - Output an execution summary mapped to TC_IDs
 *   - Mark each test as PASS or FAIL
 *
 * Outputs:
 *   reports/html-report/
 *   reports/results.json
 *   reports/execution-summary.md
 *
 * Run:
 *   node src/test/agents/execution-agent.js [module]
 *
 *   Examples:
 *   node src/test/agents/execution-agent.js           → all tests
 *   node src/test/agents/execution-agent.js login     → login only
 *   node src/test/agents/execution-agent.js customers → customers only
 * ============================================================
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const MODULE      = process.argv[2];
const REPORTS_DIR = path.join(process.cwd(), 'reports');
const RESULTS_FILE = path.join(REPORTS_DIR, 'results.json');
const SUMMARY_FILE = path.join(REPORTS_DIR, 'execution-summary.md');

function ensureDirs() {
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
}

function buildCommand() {
  const base = 'npx playwright test --config resources/config/playwright.config.js';
  if (!MODULE) return `${base} --project=regression --workers=1`;

  if (MODULE.toLowerCase() === 'login') {
    return `${base} src/test/automation/login.spec.js --project=login-tests --workers=1`;
  }
  return `${base} src/test/automation/${MODULE.toLowerCase()}.spec.js --project=regression --workers=1`;
}

function parseResults() {
  if (!fs.existsSync(RESULTS_FILE)) return [];

  const raw = JSON.parse(fs.readFileSync(RESULTS_FILE, 'utf-8'));
  const results = [];

  for (const suite of raw.suites || []) {
    for (const spec of suite.specs || []) {
      for (const test of spec.tests || []) {
        const tcIdMatch = spec.title?.match(/TC_[A-Z_0-9]+/);
        results.push({
          id: tcIdMatch ? tcIdMatch[0] : spec.title,
          status: test.results?.[0]?.status === 'passed' ? '✅ PASS' : '❌ FAIL',
          duration: `${test.results?.[0]?.duration || 0}ms`,
          error: test.results?.[0]?.error?.message?.slice(0, 100) || '',
        });
      }
    }
  }
  return results;
}

function writeSummary(results) {
  const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
  let md = `# Execution Summary\n\n`;
  md += `**Generated by:** Agent 4 — Test Execution Agent  \n`;
  md += `**Run time:** ${timestamp}  \n`;
  md += `**Module:** ${MODULE || 'All'}  \n\n`;
  md += `---\n\n`;
  md += `| TC_ID | STATUS | DURATION | ERROR |\n`;
  md += `|-------|--------|----------|-------|\n`;

  for (const r of results) {
    md += `| ${r.id} | ${r.status} | ${r.duration} | ${r.error || '-'} |\n`;
  }

  const pass = results.filter(r => r.status.includes('PASS')).length;
  const fail = results.filter(r => r.status.includes('FAIL')).length;
  md += `\n---\n\n**Total:** ${results.length} | ✅ Passed: ${pass} | ❌ Failed: ${fail}\n`;

  fs.writeFileSync(SUMMARY_FILE, md);
  console.log(`\n📊 Execution summary: ${SUMMARY_FILE}`);
}

function run() {
  ensureDirs();
  const command = buildCommand();
  console.log(`\n🚀 [Agent 4] TEST EXECUTION AGENT`);
  console.log(`   Command: ${command}\n`);

  try {
    execSync(command, { stdio: 'inherit' });
    console.log('\n✅ All tests completed.');
  } catch (_e) {
    console.log('\n⚠️  Some tests failed. Check HTML report for details.');
  }

  const results = parseResults();
  writeSummary(results);

  console.log('\n📂 View full HTML report:');
  console.log('   npx playwright show-report reports/html-report');
}

run();
