'use strict';

/**
 * AdminCmsPage.js — Scaffolded Page Object Model for admin / admin-cms.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/admin/locator-map.json (module key: "admin-cms").
 *
 * Element count at scaffold time: 86
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/admin/locator-map.json');

const L = locatorMap['admin-cms'] || {};

const ADMINCMS_URL = 'https://uat-web.xrportal.in/admin/cms';

class AdminCmsPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = ADMINCMS_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.sendOTPButton                  = page.locator(L['sendOTPButton'] && L['sendOTPButton'].selector);
    this.termsConditionsLink            = page.locator(L['termsConditionsLink'] && L['termsConditionsLink'].selector);
    this.privacyPolicyLink              = page.locator(L['privacyPolicyLink'] && L['privacyPolicyLink'].selector);
    this.enterMobileNumberInput         = page.locator(L['enterMobileNumberInput'] && L['enterMobileNumberInput'].selector);
    this.aDMINLOGINHeading              = page.locator(L['aDMINLOGINHeading'] && L['aDMINLOGINHeading'].selector);
    this.sendOTPButton2                 = page.locator(L['sendOTPButton2'] && L['sendOTPButton2'].selector);
    this.termsConditionsLink2           = page.locator(L['termsConditionsLink2'] && L['termsConditionsLink2'].selector);
    this.privacyPolicyLink2             = page.locator(L['privacyPolicyLink2'] && L['privacyPolicyLink2'].selector);
    this.enterMobileNumberInput2        = page.locator(L['enterMobileNumberInput2'] && L['enterMobileNumberInput2'].selector);
    this.aDMINLOGINHeading2             = page.locator(L['aDMINLOGINHeading2'] && L['aDMINLOGINHeading2'].selector);
    this.logoutButton                   = page.locator(L['logoutButton'] && L['logoutButton'].selector);
    this.viewTowerButton                = page.locator(L['viewTowerButton'] && L['viewTowerButton'].selector);
    this.activeInactiveButton           = page.locator(L['activeInactiveButton'] && L['activeInactiveButton'].selector);
    this.viewTowerButton2               = page.locator(L['viewTowerButton2'] && L['viewTowerButton2'].selector);
    this.activeInactiveButton2          = page.locator(L['activeInactiveButton2'] && L['activeInactiveButton2'].selector);
    this.viewTowerButton3               = page.locator(L['viewTowerButton3'] && L['viewTowerButton3'].selector);
    this.activeInactiveButton3          = page.locator(L['activeInactiveButton3'] && L['activeInactiveButton3'].selector);
    this.viewTowerButton4               = page.locator(L['viewTowerButton4'] && L['viewTowerButton4'].selector);
    this.activeInactiveButton4          = page.locator(L['activeInactiveButton4'] && L['activeInactiveButton4'].selector);
    this.viewTowerButton5               = page.locator(L['viewTowerButton5'] && L['viewTowerButton5'].selector);
    this.activeInactiveButton5          = page.locator(L['activeInactiveButton5'] && L['activeInactiveButton5'].selector);
    this.viewTowerButton6               = page.locator(L['viewTowerButton6'] && L['viewTowerButton6'].selector);
    this.activeInactiveButton6          = page.locator(L['activeInactiveButton6'] && L['activeInactiveButton6'].selector);
    this.viewTowerButton7               = page.locator(L['viewTowerButton7'] && L['viewTowerButton7'].selector);
    this.activeInactiveButton7          = page.locator(L['activeInactiveButton7'] && L['activeInactiveButton7'].selector);
    this.viewTowerButton8               = page.locator(L['viewTowerButton8'] && L['viewTowerButton8'].selector);
    this.activeInactiveButton8          = page.locator(L['activeInactiveButton8'] && L['activeInactiveButton8'].selector);
    this.viewTowerButton9               = page.locator(L['viewTowerButton9'] && L['viewTowerButton9'].selector);
    this.activeInactiveButton9          = page.locator(L['activeInactiveButton9'] && L['activeInactiveButton9'].selector);
    this.viewTowerButton10              = page.locator(L['viewTowerButton10'] && L['viewTowerButton10'].selector);
    this.activeInactiveButton10         = page.locator(L['activeInactiveButton10'] && L['activeInactiveButton10'].selector);
    this.viewTowerButton11              = page.locator(L['viewTowerButton11'] && L['viewTowerButton11'].selector);
    this.activeInactiveButton11         = page.locator(L['activeInactiveButton11'] && L['activeInactiveButton11'].selector);
    this.viewTowerButton12              = page.locator(L['viewTowerButton12'] && L['viewTowerButton12'].selector);
    this.activeInactiveButton12         = page.locator(L['activeInactiveButton12'] && L['activeInactiveButton12'].selector);
    this.viewTowerButton13              = page.locator(L['viewTowerButton13'] && L['viewTowerButton13'].selector);
    this.activeInactiveButton13         = page.locator(L['activeInactiveButton13'] && L['activeInactiveButton13'].selector);
    this.viewTowerButton14              = page.locator(L['viewTowerButton14'] && L['viewTowerButton14'].selector);
    this.activeInactiveButton14         = page.locator(L['activeInactiveButton14'] && L['activeInactiveButton14'].selector);
    this.viewTowerButton15              = page.locator(L['viewTowerButton15'] && L['viewTowerButton15'].selector);
    this.activeInactiveButton15         = page.locator(L['activeInactiveButton15'] && L['activeInactiveButton15'].selector);
    this.viewTowerButton16              = page.locator(L['viewTowerButton16'] && L['viewTowerButton16'].selector);
    this.activeInactiveButton16         = page.locator(L['activeInactiveButton16'] && L['activeInactiveButton16'].selector);
    this.viewTowerButton17              = page.locator(L['viewTowerButton17'] && L['viewTowerButton17'].selector);
    this.activeInactiveButton17         = page.locator(L['activeInactiveButton17'] && L['activeInactiveButton17'].selector);
    this.viewTowerButton18              = page.locator(L['viewTowerButton18'] && L['viewTowerButton18'].selector);
    this.activeInactiveButton18         = page.locator(L['activeInactiveButton18'] && L['activeInactiveButton18'].selector);
    this.updateTowerConfigurationButton = page.locator(L['updateTowerConfigurationButton'] && L['updateTowerConfigurationButton'].selector);
    this.sampleFileDownloadButton       = page.locator(L['sampleFileDownloadButton'] && L['sampleFileDownloadButton'].selector);
    this.uploadFileButton               = page.locator(L['uploadFileButton'] && L['uploadFileButton'].selector);
    this.submitButton                   = page.locator(L['submitButton'] && L['submitButton'].selector);
    this.sampleFileDownloadButton2      = page.locator(L['sampleFileDownloadButton2'] && L['sampleFileDownloadButton2'].selector);
    this.uploadFileButton2              = page.locator(L['uploadFileButton2'] && L['uploadFileButton2'].selector);
    this.submitButton2                  = page.locator(L['submitButton2'] && L['submitButton2'].selector);
    this.availableUnitInventoryDownloadButton = page.locator(L['availableUnitInventoryDownloadButton'] && L['availableUnitInventoryDownloadButton'].selector);
    this.uploadFileButton3              = page.locator(L['uploadFileButton3'] && L['uploadFileButton3'].selector);
    this.submitButton3                  = page.locator(L['submitButton3'] && L['submitButton3'].selector);
    this.sampleFileDownloadButton3      = page.locator(L['sampleFileDownloadButton3'] && L['sampleFileDownloadButton3'].selector);
    this.uploadFileButton4              = page.locator(L['uploadFileButton4'] && L['uploadFileButton4'].selector);
    this.submitButton4                  = page.locator(L['submitButton4'] && L['submitButton4'].selector);
    this.sampleFileDownloadButton4      = page.locator(L['sampleFileDownloadButton4'] && L['sampleFileDownloadButton4'].selector);
    this.uploadFileButton5              = page.locator(L['uploadFileButton5'] && L['uploadFileButton5'].selector);
    this.submitButton5                  = page.locator(L['submitButton5'] && L['submitButton5'].selector);
    this.sampleFileDownloadButton5      = page.locator(L['sampleFileDownloadButton5'] && L['sampleFileDownloadButton5'].selector);
    this.uploadFileButton6              = page.locator(L['uploadFileButton6'] && L['uploadFileButton6'].selector);
    this.submitButton6                  = page.locator(L['submitButton6'] && L['submitButton6'].selector);
    this.activeInactiveButton19         = page.locator(L['activeInactiveButton19'] && L['activeInactiveButton19'].selector);
    this.submitButton7                  = page.locator(L['submitButton7'] && L['submitButton7'].selector);
    this.updateButton                   = page.locator(L['updateButton'] && L['updateButton'].selector);
    this.customersLink                  = page.locator(L['customersLink'] && L['customersLink'].selector);
    this.configLink                     = page.locator(L['configLink'] && L['configLink'].selector);
    this.allocationLink                 = page.locator(L['allocationLink'] && L['allocationLink'].selector);
    this.offersLink                     = page.locator(L['offersLink'] && L['offersLink'].selector);
    this.towersLink                     = page.locator(L['towersLink'] && L['towersLink'].selector);
    this.jBPMgmtLink                    = page.locator(L['jBPMgmtLink'] && L['jBPMgmtLink'].selector);
    this.channelPartnersLink            = page.locator(L['channelPartnersLink'] && L['channelPartnersLink'].selector);
    this.salesManagersLink              = page.locator(L['salesManagersLink'] && L['salesManagersLink'].selector);
    this.transactionsLink               = page.locator(L['transactionsLink'] && L['transactionsLink'].selector);
    this.cMSLink                        = page.locator(L['cMSLink'] && L['cMSLink'].selector);
    this.checkboxInput                  = page.locator(L['checkboxInput'] && L['checkboxInput'].selector);
    this.rcSelect0                      = page.locator(L['rcSelect0'] && L['rcSelect0'].selector);
    this.checkboxInput2                 = page.locator(L['checkboxInput2'] && L['checkboxInput2'].selector);
    this.rcSelect1                      = page.locator(L['rcSelect1'] && L['rcSelect1'].selector);
    this.checkboxInput3                 = page.locator(L['checkboxInput3'] && L['checkboxInput3'].selector);
    this.rcSelect2                      = page.locator(L['rcSelect2'] && L['rcSelect2'].selector);
    this.rcSelect3                      = page.locator(L['rcSelect3'] && L['rcSelect3'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { AdminCmsPage };
