'use strict';

/**
 * AllocationPage.js — Scaffolded Page Object Model for admin / allocation.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/admin/locator-map.json (module key: "allocation").
 *
 * Element count at scaffold time: 34
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/admin/locator-map.json');

const L = locatorMap['allocation'] || {};

const ALLOCATION_URL = 'https://uat-web.xrportal.in/admin/allocation';

class AllocationPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = ALLOCATION_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.sendOTPButton                  = page.locator(L['sendOTPButton'] && L['sendOTPButton'].selector);
    this.termsConditionsLink            = page.locator(L['termsConditionsLink'] && L['termsConditionsLink'].selector);
    this.privacyPolicyLink              = page.locator(L['privacyPolicyLink'] && L['privacyPolicyLink'].selector);
    this.enterMobileNumberInput         = page.locator(L['enterMobileNumberInput'] && L['enterMobileNumberInput'].selector);
    this.aDMINLOGINHeading              = page.locator(L['aDMINLOGINHeading'] && L['aDMINLOGINHeading'].selector);
    this.sendOTPButton2                 = page.locator(L['sendOTPButton2'] && L['sendOTPButton2'].selector);
    this.termsConditionsLink2           = page.locator(L['termsConditionsLink2'] && L['termsConditionsLink2'].selector);
    this.privacyPolicyLink2             = page.locator(L['privacyPolicyLink2'] && L['privacyPolicyLink2'].selector);
    this.enterMobileNumberInput2        = page.locator(L['enterMobileNumberInput2'] && L['enterMobileNumberInput2'].selector);
    this.aDMINLOGINHeading2             = page.locator(L['aDMINLOGINHeading2'] && L['aDMINLOGINHeading2'].selector);
    this.logoutButton                   = page.locator(L['logoutButton'] && L['logoutButton'].selector);
    this.resetButton                    = page.locator(L['resetButton'] && L['resetButton'].selector);
    this.saveCampaignButton             = page.locator(L['saveCampaignButton'] && L['saveCampaignButton'].selector);
    this.refreshButton                  = page.locator(L['refreshButton'] && L['refreshButton'].selector);
    this.customersLink                  = page.locator(L['customersLink'] && L['customersLink'].selector);
    this.configLink                     = page.locator(L['configLink'] && L['configLink'].selector);
    this.allocationLink                 = page.locator(L['allocationLink'] && L['allocationLink'].selector);
    this.offersLink                     = page.locator(L['offersLink'] && L['offersLink'].selector);
    this.towersLink                     = page.locator(L['towersLink'] && L['towersLink'].selector);
    this.jBPMgmtLink                    = page.locator(L['jBPMgmtLink'] && L['jBPMgmtLink'].selector);
    this.channelPartnersLink            = page.locator(L['channelPartnersLink'] && L['channelPartnersLink'].selector);
    this.salesManagersLink              = page.locator(L['salesManagersLink'] && L['salesManagersLink'].selector);
    this.transactionsLink               = page.locator(L['transactionsLink'] && L['transactionsLink'].selector);
    this.cMSLink                        = page.locator(L['cMSLink'] && L['cMSLink'].selector);
    this.rcSelect0                      = page.locator(L['rcSelect0'] && L['rcSelect0'].selector);
    this.enterCampaignNameInput         = page.locator(L['enterCampaignNameInput'] && L['enterCampaignNameInput'].selector);
    this.rcSelect1                      = page.locator(L['rcSelect1'] && L['rcSelect1'].selector);
    this.selectDateInput                = page.locator(L['selectDateInput'] && L['selectDateInput'].selector);
    this.selectDateInput2               = page.locator(L['selectDateInput2'] && L['selectDateInput2'].selector);
    this.rcSelect2                      = page.locator(L['rcSelect2'] && L['rcSelect2'].selector);
    this.rcSelect3                      = page.locator(L['rcSelect3'] && L['rcSelect3'].selector);
    this.rcSelect4                      = page.locator(L['rcSelect4'] && L['rcSelect4'].selector);
    this.campaignNameSearch             = page.locator(L['campaignNameSearch'] && L['campaignNameSearch'].selector);
    this.descriptionInput               = page.locator(L['descriptionInput'] && L['descriptionInput'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { AllocationPage };
