'use strict';

/**
 * ChannelPartnersPage.js — Scaffolded Page Object Model for admin / channel-partners.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/admin/locator-map.json (module key: "channel-partners").
 *
 * Element count at scaffold time: 59
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/admin/locator-map.json');

const L = locatorMap['channel-partners'] || {};

const CHANNELPARTNERS_URL = 'https://uat-web.xrportal.in/admin/channel-partners';

class ChannelPartnersPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = CHANNELPARTNERS_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.sendOTPButton                  = page.locator(L['sendOTPButton'] && L['sendOTPButton'].selector);
    this.termsConditionsLink            = page.locator(L['termsConditionsLink'] && L['termsConditionsLink'].selector);
    this.privacyPolicyLink              = page.locator(L['privacyPolicyLink'] && L['privacyPolicyLink'].selector);
    this.enterMobileNumberInput         = page.locator(L['enterMobileNumberInput'] && L['enterMobileNumberInput'].selector);
    this.aDMINLOGINHeading              = page.locator(L['aDMINLOGINHeading'] && L['aDMINLOGINHeading'].selector);
    this.sendOTPButton2                 = page.locator(L['sendOTPButton2'] && L['sendOTPButton2'].selector);
    this.termsConditionsLink2           = page.locator(L['termsConditionsLink2'] && L['termsConditionsLink2'].selector);
    this.privacyPolicyLink2             = page.locator(L['privacyPolicyLink2'] && L['privacyPolicyLink2'].selector);
    this.enterMobileNumberInput2        = page.locator(L['enterMobileNumberInput2'] && L['enterMobileNumberInput2'].selector);
    this.aDMINLOGINHeading2             = page.locator(L['aDMINLOGINHeading2'] && L['aDMINLOGINHeading2'].selector);
    this.logoutButton                   = page.locator(L['logoutButton'] && L['logoutButton'].selector);
    this.mapMasterCP0Button             = page.locator(L['mapMasterCP0Button'] && L['mapMasterCP0Button'].selector);
    this.resetFiltersButton             = page.locator(L['resetFiltersButton'] && L['resetFiltersButton'].selector);
    this.refreshButton                  = page.locator(L['refreshButton'] && L['refreshButton'].selector);
    this.cpRowAction                    = page.locator(L['cpRowAction'] && L['cpRowAction'].selector);
    this.cpRowAction2                   = page.locator(L['cpRowAction2'] && L['cpRowAction2'].selector);
    this.cpRowAction3                   = page.locator(L['cpRowAction3'] && L['cpRowAction3'].selector);
    this.cpRowAction4                   = page.locator(L['cpRowAction4'] && L['cpRowAction4'].selector);
    this.cpRowAction5                   = page.locator(L['cpRowAction5'] && L['cpRowAction5'].selector);
    this.cpRowAction6                   = page.locator(L['cpRowAction6'] && L['cpRowAction6'].selector);
    this.cpRowAction7                   = page.locator(L['cpRowAction7'] && L['cpRowAction7'].selector);
    this.cpRowAction8                   = page.locator(L['cpRowAction8'] && L['cpRowAction8'].selector);
    this.cpRowAction9                   = page.locator(L['cpRowAction9'] && L['cpRowAction9'].selector);
    this.cpRowAction10                  = page.locator(L['cpRowAction10'] && L['cpRowAction10'].selector);
    this.cpRowAction11                  = page.locator(L['cpRowAction11'] && L['cpRowAction11'].selector);
    this.cpRowAction12                  = page.locator(L['cpRowAction12'] && L['cpRowAction12'].selector);
    this.cpRowAction13                  = page.locator(L['cpRowAction13'] && L['cpRowAction13'].selector);
    this.cpRowAction14                  = page.locator(L['cpRowAction14'] && L['cpRowAction14'].selector);
    this.cpRowAction15                  = page.locator(L['cpRowAction15'] && L['cpRowAction15'].selector);
    this.cpRowAction16                  = page.locator(L['cpRowAction16'] && L['cpRowAction16'].selector);
    this.cpRowAction17                  = page.locator(L['cpRowAction17'] && L['cpRowAction17'].selector);
    this.cpRowAction18                  = page.locator(L['cpRowAction18'] && L['cpRowAction18'].selector);
    this.cpRowAction19                  = page.locator(L['cpRowAction19'] && L['cpRowAction19'].selector);
    this.cpRowAction20                  = page.locator(L['cpRowAction20'] && L['cpRowAction20'].selector);
    this.customersLink                  = page.locator(L['customersLink'] && L['customersLink'].selector);
    this.configLink                     = page.locator(L['configLink'] && L['configLink'].selector);
    this.allocationLink                 = page.locator(L['allocationLink'] && L['allocationLink'].selector);
    this.offersLink                     = page.locator(L['offersLink'] && L['offersLink'].selector);
    this.towersLink                     = page.locator(L['towersLink'] && L['towersLink'].selector);
    this.jBPMgmtLink                    = page.locator(L['jBPMgmtLink'] && L['jBPMgmtLink'].selector);
    this.channelPartnersLink            = page.locator(L['channelPartnersLink'] && L['channelPartnersLink'].selector);
    this.salesManagersLink              = page.locator(L['salesManagersLink'] && L['salesManagersLink'].selector);
    this.transactionsLink               = page.locator(L['transactionsLink'] && L['transactionsLink'].selector);
    this.cMSLink                        = page.locator(L['cMSLink'] && L['cMSLink'].selector);
    this.searchByPhoneInput             = page.locator(L['searchByPhoneInput'] && L['searchByPhoneInput'].selector);
    this.selectAll                      = page.locator(L['selectAll'] && L['selectAll'].selector);
    this.selectAll2                     = page.locator(L['selectAll2'] && L['selectAll2'].selector);
    this.checkboxInput                  = page.locator(L['checkboxInput'] && L['checkboxInput'].selector);
    this.checkboxInput2                 = page.locator(L['checkboxInput2'] && L['checkboxInput2'].selector);
    this.checkboxInput3                 = page.locator(L['checkboxInput3'] && L['checkboxInput3'].selector);
    this.checkboxInput4                 = page.locator(L['checkboxInput4'] && L['checkboxInput4'].selector);
    this.checkboxInput5                 = page.locator(L['checkboxInput5'] && L['checkboxInput5'].selector);
    this.checkboxInput6                 = page.locator(L['checkboxInput6'] && L['checkboxInput6'].selector);
    this.checkboxInput7                 = page.locator(L['checkboxInput7'] && L['checkboxInput7'].selector);
    this.checkboxInput8                 = page.locator(L['checkboxInput8'] && L['checkboxInput8'].selector);
    this.checkboxInput9                 = page.locator(L['checkboxInput9'] && L['checkboxInput9'].selector);
    this.checkboxInput10                = page.locator(L['checkboxInput10'] && L['checkboxInput10'].selector);
    this.rcSelect0                      = page.locator(L['rcSelect0'] && L['rcSelect0'].selector);
    this.el2709ChannelPartnersHeading   = page.locator(L['2709ChannelPartnersHeading'] && L['2709ChannelPartnersHeading'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { ChannelPartnersPage };
