'use strict';

/**
 * ConfigPage.js — Scaffolded Page Object Model for admin / config.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/admin/locator-map.json (module key: "config").
 *
 * Element count at scaffold time: 40
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/admin/locator-map.json');

const L = locatorMap['config'] || {};

const CONFIG_URL = 'https://uat-web.xrportal.in/admin/config';

class ConfigPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = CONFIG_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.sendOTPButton                  = page.locator(L['sendOTPButton'] && L['sendOTPButton'].selector);
    this.termsConditionsLink            = page.locator(L['termsConditionsLink'] && L['termsConditionsLink'].selector);
    this.privacyPolicyLink              = page.locator(L['privacyPolicyLink'] && L['privacyPolicyLink'].selector);
    this.enterMobileNumberInput         = page.locator(L['enterMobileNumberInput'] && L['enterMobileNumberInput'].selector);
    this.aDMINLOGINHeading              = page.locator(L['aDMINLOGINHeading'] && L['aDMINLOGINHeading'].selector);
    this.sendOTPButton2                 = page.locator(L['sendOTPButton2'] && L['sendOTPButton2'].selector);
    this.termsConditionsLink2           = page.locator(L['termsConditionsLink2'] && L['termsConditionsLink2'].selector);
    this.privacyPolicyLink2             = page.locator(L['privacyPolicyLink2'] && L['privacyPolicyLink2'].selector);
    this.enterMobileNumberInput2        = page.locator(L['enterMobileNumberInput2'] && L['enterMobileNumberInput2'].selector);
    this.aDMINLOGINHeading2             = page.locator(L['aDMINLOGINHeading2'] && L['aDMINLOGINHeading2'].selector);
    this.logoutButton                   = page.locator(L['logoutButton'] && L['logoutButton'].selector);
    this.cancelBulkUnitsButton          = page.locator(L['cancelBulkUnitsButton'] && L['cancelBulkUnitsButton'].selector);
    this.filterButton                   = page.locator(L['filterButton'] && L['filterButton'].selector);
    this.refreshButton                  = page.locator(L['refreshButton'] && L['refreshButton'].selector);
    this.downloadButton                 = page.locator(L['downloadButton'] && L['downloadButton'].selector);
    this.copyIcon                       = page.locator(L['copyIcon'] && L['copyIcon'].selector);
    this.copyIcon2                      = page.locator(L['copyIcon2'] && L['copyIcon2'].selector);
    this.downloadYourUnitDetailsButton  = page.locator(L['downloadYourUnitDetailsButton'] && L['downloadYourUnitDetailsButton'].selector);
    this.copyIcon3                      = page.locator(L['copyIcon3'] && L['copyIcon3'].selector);
    this.downloadYourUnitDetailsButton2 = page.locator(L['downloadYourUnitDetailsButton2'] && L['downloadYourUnitDetailsButton2'].selector);
    this.copyIcon4                      = page.locator(L['copyIcon4'] && L['copyIcon4'].selector);
    this.copyIcon5                      = page.locator(L['copyIcon5'] && L['copyIcon5'].selector);
    this.copyIcon6                      = page.locator(L['copyIcon6'] && L['copyIcon6'].selector);
    this.copyIcon7                      = page.locator(L['copyIcon7'] && L['copyIcon7'].selector);
    this.copyIcon8                      = page.locator(L['copyIcon8'] && L['copyIcon8'].selector);
    this.copyIcon9                      = page.locator(L['copyIcon9'] && L['copyIcon9'].selector);
    this.copyIcon10                     = page.locator(L['copyIcon10'] && L['copyIcon10'].selector);
    this.customersLink                  = page.locator(L['customersLink'] && L['customersLink'].selector);
    this.configLink                     = page.locator(L['configLink'] && L['configLink'].selector);
    this.allocationLink                 = page.locator(L['allocationLink'] && L['allocationLink'].selector);
    this.offersLink                     = page.locator(L['offersLink'] && L['offersLink'].selector);
    this.towersLink                     = page.locator(L['towersLink'] && L['towersLink'].selector);
    this.jBPMgmtLink                    = page.locator(L['jBPMgmtLink'] && L['jBPMgmtLink'].selector);
    this.channelPartnersLink            = page.locator(L['channelPartnersLink'] && L['channelPartnersLink'].selector);
    this.salesManagersLink              = page.locator(L['salesManagersLink'] && L['salesManagersLink'].selector);
    this.transactionsLink               = page.locator(L['transactionsLink'] && L['transactionsLink'].selector);
    this.cMSLink                        = page.locator(L['cMSLink'] && L['cMSLink'].selector);
    this.searchByPhoneInput             = page.locator(L['searchByPhoneInput'] && L['searchByPhoneInput'].selector);
    this.rcSelect0                      = page.locator(L['rcSelect0'] && L['rcSelect0'].selector);
    this.el9682RegistrationRecordsHeading = page.locator(L['9682RegistrationRecordsHeading'] && L['9682RegistrationRecordsHeading'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { ConfigPage };
