'use strict';

/**
 * SalesManagersPage.js — Scaffolded Page Object Model for admin / sales-managers.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/admin/locator-map.json (module key: "sales-managers").
 *
 * Element count at scaffold time: 34
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/admin/locator-map.json');

const L = locatorMap['sales-managers'] || {};

const SALESMANAGERS_URL = 'https://uat-web.xrportal.in/admin/sales-managers';

class SalesManagersPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = SALESMANAGERS_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.sendOTPButton                  = page.locator(L['sendOTPButton'] && L['sendOTPButton'].selector);
    this.termsConditionsLink            = page.locator(L['termsConditionsLink'] && L['termsConditionsLink'].selector);
    this.privacyPolicyLink              = page.locator(L['privacyPolicyLink'] && L['privacyPolicyLink'].selector);
    this.enterMobileNumberInput         = page.locator(L['enterMobileNumberInput'] && L['enterMobileNumberInput'].selector);
    this.aDMINLOGINHeading              = page.locator(L['aDMINLOGINHeading'] && L['aDMINLOGINHeading'].selector);
    this.sendOTPButton2                 = page.locator(L['sendOTPButton2'] && L['sendOTPButton2'].selector);
    this.termsConditionsLink2           = page.locator(L['termsConditionsLink2'] && L['termsConditionsLink2'].selector);
    this.privacyPolicyLink2             = page.locator(L['privacyPolicyLink2'] && L['privacyPolicyLink2'].selector);
    this.enterMobileNumberInput2        = page.locator(L['enterMobileNumberInput2'] && L['enterMobileNumberInput2'].selector);
    this.aDMINLOGINHeading2             = page.locator(L['aDMINLOGINHeading2'] && L['aDMINLOGINHeading2'].selector);
    this.logoutButton                   = page.locator(L['logoutButton'] && L['logoutButton'].selector);
    this.settingsButton                 = page.locator(L['settingsButton'] && L['settingsButton'].selector);
    this.addSalesManagerButton          = page.locator(L['addSalesManagerButton'] && L['addSalesManagerButton'].selector);
    this.editButton                     = page.locator(L['editButton'] && L['editButton'].selector);
    this.editButton2                    = page.locator(L['editButton2'] && L['editButton2'].selector);
    this.editButton3                    = page.locator(L['editButton3'] && L['editButton3'].selector);
    this.editButton4                    = page.locator(L['editButton4'] && L['editButton4'].selector);
    this.editButton5                    = page.locator(L['editButton5'] && L['editButton5'].selector);
    this.editButton6                    = page.locator(L['editButton6'] && L['editButton6'].selector);
    this.editButton7                    = page.locator(L['editButton7'] && L['editButton7'].selector);
    this.editButton8                    = page.locator(L['editButton8'] && L['editButton8'].selector);
    this.editButton9                    = page.locator(L['editButton9'] && L['editButton9'].selector);
    this.editButton10                   = page.locator(L['editButton10'] && L['editButton10'].selector);
    this.customersLink                  = page.locator(L['customersLink'] && L['customersLink'].selector);
    this.configLink                     = page.locator(L['configLink'] && L['configLink'].selector);
    this.allocationLink                 = page.locator(L['allocationLink'] && L['allocationLink'].selector);
    this.offersLink                     = page.locator(L['offersLink'] && L['offersLink'].selector);
    this.towersLink                     = page.locator(L['towersLink'] && L['towersLink'].selector);
    this.jBPMgmtLink                    = page.locator(L['jBPMgmtLink'] && L['jBPMgmtLink'].selector);
    this.channelPartnersLink            = page.locator(L['channelPartnersLink'] && L['channelPartnersLink'].selector);
    this.salesManagersLink              = page.locator(L['salesManagersLink'] && L['salesManagersLink'].selector);
    this.transactionsLink               = page.locator(L['transactionsLink'] && L['transactionsLink'].selector);
    this.cMSLink                        = page.locator(L['cMSLink'] && L['cMSLink'].selector);
    this.searchByNameEmailOrPhoneInput  = page.locator(L['searchByNameEmailOrPhoneInput'] && L['searchByNameEmailOrPhoneInput'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { SalesManagersPage };
