'use strict';

/**
 * TowersPage.js — Scaffolded Page Object Model for admin / towers.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/admin/locator-map.json (module key: "towers").
 *
 * Element count at scaffold time: 23
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/admin/locator-map.json');

const L = locatorMap['towers'] || {};

const TOWERS_URL = 'https://uat-web.xrportal.in/admin/towers';

class TowersPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = TOWERS_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.sendOTPButton                  = page.locator(L['sendOTPButton'] && L['sendOTPButton'].selector);
    this.termsConditionsLink            = page.locator(L['termsConditionsLink'] && L['termsConditionsLink'].selector);
    this.privacyPolicyLink              = page.locator(L['privacyPolicyLink'] && L['privacyPolicyLink'].selector);
    this.enterMobileNumberInput         = page.locator(L['enterMobileNumberInput'] && L['enterMobileNumberInput'].selector);
    this.aDMINLOGINHeading              = page.locator(L['aDMINLOGINHeading'] && L['aDMINLOGINHeading'].selector);
    this.sendOTPButton2                 = page.locator(L['sendOTPButton2'] && L['sendOTPButton2'].selector);
    this.termsConditionsLink2           = page.locator(L['termsConditionsLink2'] && L['termsConditionsLink2'].selector);
    this.privacyPolicyLink2             = page.locator(L['privacyPolicyLink2'] && L['privacyPolicyLink2'].selector);
    this.enterMobileNumberInput2        = page.locator(L['enterMobileNumberInput2'] && L['enterMobileNumberInput2'].selector);
    this.aDMINLOGINHeading2             = page.locator(L['aDMINLOGINHeading2'] && L['aDMINLOGINHeading2'].selector);
    this.logoutButton                   = page.locator(L['logoutButton'] && L['logoutButton'].selector);
    this.reset                          = page.locator(L['reset'] && L['reset'].selector);
    this.preBookedPaymentsButton        = page.locator(L['preBookedPaymentsButton'] && L['preBookedPaymentsButton'].selector);
    this.customersLink                  = page.locator(L['customersLink'] && L['customersLink'].selector);
    this.configLink                     = page.locator(L['configLink'] && L['configLink'].selector);
    this.allocationLink                 = page.locator(L['allocationLink'] && L['allocationLink'].selector);
    this.offersLink                     = page.locator(L['offersLink'] && L['offersLink'].selector);
    this.towersLink                     = page.locator(L['towersLink'] && L['towersLink'].selector);
    this.jBPMgmtLink                    = page.locator(L['jBPMgmtLink'] && L['jBPMgmtLink'].selector);
    this.channelPartnersLink            = page.locator(L['channelPartnersLink'] && L['channelPartnersLink'].selector);
    this.salesManagersLink              = page.locator(L['salesManagersLink'] && L['salesManagersLink'].selector);
    this.transactionsLink               = page.locator(L['transactionsLink'] && L['transactionsLink'].selector);
    this.cMSLink                        = page.locator(L['cMSLink'] && L['cMSLink'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { TowersPage };
