'use strict';

/**
 * CallbackRequestsPage.js — Scaffolded Page Object Model for sales-manager / callback-requests.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/sales-manager/locator-map.json (module key: "callback-requests").
 *
 * Element count at scaffold time: 39
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/sales-manager/locator-map.json');

const L = locatorMap['callback-requests'] || {};

const CALLBACKREQUESTS_URL = 'https://uat-web.xrportal.in/sales-manager/callback-requests';

class CallbackRequestsPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = CALLBACKREQUESTS_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.logoutButton                   = page.locator(L['logoutButton'] && L['logoutButton'].selector);
    this.assign0Button                  = page.locator(L['assign0Button'] && L['assign0Button'].selector);
    this.createCallbackRequestButton    = page.locator(L['createCallbackRequestButton'] && L['createCallbackRequestButton'].selector);
    this.refreshButton                  = page.locator(L['refreshButton'] && L['refreshButton'].selector);
    this.exportButton                   = page.locator(L['exportButton'] && L['exportButton'].selector);
    this.sendInviteButton               = page.locator(L['sendInviteButton'] && L['sendInviteButton'].selector);
    this.meetingDoneButton              = page.locator(L['meetingDoneButton'] && L['meetingDoneButton'].selector);
    this.completedButton                = page.locator(L['completedButton'] && L['completedButton'].selector);
    this.resendInviteButton             = page.locator(L['resendInviteButton'] && L['resendInviteButton'].selector);
    this.meetingDoneButton2             = page.locator(L['meetingDoneButton2'] && L['meetingDoneButton2'].selector);
    this.copyLinkBtn                    = page.locator(L['copyLinkBtn'] && L['copyLinkBtn'].selector);
    this.completedButton2               = page.locator(L['completedButton2'] && L['completedButton2'].selector);
    this.sendInviteButton2              = page.locator(L['sendInviteButton2'] && L['sendInviteButton2'].selector);
    this.meetingDoneButton3             = page.locator(L['meetingDoneButton3'] && L['meetingDoneButton3'].selector);
    this.completedButton3               = page.locator(L['completedButton3'] && L['completedButton3'].selector);
    this.completedButton4               = page.locator(L['completedButton4'] && L['completedButton4'].selector);
    this.completedButton5               = page.locator(L['completedButton5'] && L['completedButton5'].selector);
    this.completedButton6               = page.locator(L['completedButton6'] && L['completedButton6'].selector);
    this.completedButton7               = page.locator(L['completedButton7'] && L['completedButton7'].selector);
    this.callbackRequestsLink           = page.locator(L['callbackRequestsLink'] && L['callbackRequestsLink'].selector);
    this.towersLink                     = page.locator(L['towersLink'] && L['towersLink'].selector);
    this.allocationLink                 = page.locator(L['allocationLink'] && L['allocationLink'].selector);
    this.startDateInput                 = page.locator(L['startDateInput'] && L['startDateInput'].selector);
    this.endDateInput                   = page.locator(L['endDateInput'] && L['endDateInput'].selector);
    this.searchByNamePhoneEmailRegNoInput = page.locator(L['searchByNamePhoneEmailRegNoInput'] && L['searchByNamePhoneEmailRegNoInput'].selector);
    this.rcSelect0                      = page.locator(L['rcSelect0'] && L['rcSelect0'].selector);
    this.selectAll                      = page.locator(L['selectAll'] && L['selectAll'].selector);
    this.selectAll2                     = page.locator(L['selectAll2'] && L['selectAll2'].selector);
    this.checkboxInput                  = page.locator(L['checkboxInput'] && L['checkboxInput'].selector);
    this.checkboxInput2                 = page.locator(L['checkboxInput2'] && L['checkboxInput2'].selector);
    this.checkboxInput3                 = page.locator(L['checkboxInput3'] && L['checkboxInput3'].selector);
    this.checkboxInput4                 = page.locator(L['checkboxInput4'] && L['checkboxInput4'].selector);
    this.checkboxInput5                 = page.locator(L['checkboxInput5'] && L['checkboxInput5'].selector);
    this.checkboxInput6                 = page.locator(L['checkboxInput6'] && L['checkboxInput6'].selector);
    this.checkboxInput7                 = page.locator(L['checkboxInput7'] && L['checkboxInput7'].selector);
    this.checkboxInput8                 = page.locator(L['checkboxInput8'] && L['checkboxInput8'].selector);
    this.checkboxInput9                 = page.locator(L['checkboxInput9'] && L['checkboxInput9'].selector);
    this.checkboxInput10                = page.locator(L['checkboxInput10'] && L['checkboxInput10'].selector);
    this.rcSelect1                      = page.locator(L['rcSelect1'] && L['rcSelect1'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { CallbackRequestsPage };
