'use strict';

/**
 * PhysicalAllocationPage.js — Scaffolded Page Object Model for sales-manager / physical-allocation.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/sales-manager/locator-map.json (module key: "physical-allocation").
 *
 * Element count at scaffold time: 6
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/sales-manager/locator-map.json');

const L = locatorMap['physical-allocation'] || {};

const PHYSICALALLOCATION_URL = 'https://uat-web.xrportal.in/sales-manager/physical-allocation';

class PhysicalAllocationPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = PHYSICALALLOCATION_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.logoutButton                   = page.locator(L['logoutButton'] && L['logoutButton'].selector);
    this.refreshButton                  = page.locator(L['refreshButton'] && L['refreshButton'].selector);
    this.callbackRequestsLink           = page.locator(L['callbackRequestsLink'] && L['callbackRequestsLink'].selector);
    this.towersLink                     = page.locator(L['towersLink'] && L['towersLink'].selector);
    this.allocationLink                 = page.locator(L['allocationLink'] && L['allocationLink'].selector);
    this.noActiveCampaignHeading        = page.locator(L['noActiveCampaignHeading'] && L['noActiveCampaignHeading'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { PhysicalAllocationPage };
