'use strict';

/**
 * TowerHeatmapPage.js — Scaffolded Page Object Model for sales-manager / tower-heatmap.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/sales-manager/locator-map.json (module key: "tower-heatmap").
 *
 * Element count at scaffold time: 5
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/sales-manager/locator-map.json');

const L = locatorMap['tower-heatmap'] || {};

const TOWERHEATMAP_URL = 'https://uat-web.xrportal.in/sales-manager/towers';

class TowerHeatmapPage extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = TOWERHEATMAP_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
    this.logoutButton                   = page.locator(L['logoutButton'] && L['logoutButton'].selector);
    this.reset                          = page.locator(L['reset'] && L['reset'].selector);
    this.callbackRequestsLink           = page.locator(L['callbackRequestsLink'] && L['callbackRequestsLink'].selector);
    this.towersLink                     = page.locator(L['towersLink'] && L['towersLink'].selector);
    this.allocationLink                 = page.locator(L['allocationLink'] && L['allocationLink'].selector);
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { TowerHeatmapPage };
