// scripts/scaffold-poms.js
// Generates skeleton Page Object Model files from locators/<portal>/locator-map.json.
// Skips POMs that already exist (does not overwrite hand-written ones).
//
// Output: automation-repository/pages/<portal>/<Module>Page.js
//
// Run:  node scripts/scaffold-poms.js                     (all 4 portals)
//       node scripts/scaffold-poms.js --portal=sm
//       node scripts/scaffold-poms.js --portal=admin --force   (overwrite)

'use strict';
const fs   = require('fs');
const path = require('path');

const ROOT       = path.join(__dirname, '..');
const LOCATORS   = path.join(ROOT, 'locators');
const POM_BASE   = path.join(ROOT, 'automation-repository', 'pages');

// ─── Portal → folder mapping ─────────────────────────────────────────────────

const PORTAL_FOLDER = {
  'admin':           { pomDir: 'admin',            urlBase: 'https://uat-web.xrportal.in' },
  'buyer':           { pomDir: 'buyer',            urlBase: 'https://uat.xrportal.in' },
  'channel-partner': { pomDir: 'channel-partner',  urlBase: 'https://uat-web.xrportal.in' },
  'sales-manager':   { pomDir: 'sales-manager',    urlBase: 'https://uat-web.xrportal.in' },
};

// Module → URL path (matches scripts/crawl-locators.js)
const MODULE_PATHS = {
  'admin': {
    'login': '/admin', 'dashboard': '/admin/dashboard', 'customers': '/admin/customers',
    'sales-managers': '/admin/sales-managers', 'payment-transactions': '/admin/payment-transactions',
    'allocation': '/admin/allocation', 'towers': '/admin/towers', 'jbp': '/admin/jbp',
    'offers': '/admin/offers', 'channel-partners': '/admin/channel-partners',
    'admin-cms': '/admin/cms', 'config': '/admin/config',
  },
  'buyer': {
    'registration-login': '/', 'home-dashboard': '/home', 'kyc': '/kyc',
    'unit-details': '/unit-details', 'project-information': '/project',
    'payment-schedule': '/payment-schedule', 'home-loan': '/homeloan',
    'allocation-experience': '/allotment', 'callback-request': '/callback-request',
    'support-tickets': '/support', 'work-progress': '/work-progress',
  },
  'channel-partner': {
    'login': '/login', 'leads-management': '/leads', 'customer-registration': '/dashboard',
    'kyc-assistance': '/kyc', 'jbp-submission': '/jbp', 'project-information': '/project1',
  },
  'sales-manager': {
    'login': '/sales-manager', 'callback-requests': '/sales-manager/callback-requests',
    'tower-heatmap': '/sales-manager/towers', 'physical-allocation': '/sales-manager/physical-allocation',
  },
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

function pascal(slug) {
  return slug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}

function safeJsKey(k) {
  // Strip non-identifier chars, ensure starts with letter
  let s = k.replace(/[^a-zA-Z0-9_]/g, '');
  if (!/^[a-zA-Z_]/.test(s)) s = 'el' + s;
  return s;
}

// ─── Generator ───────────────────────────────────────────────────────────────

function generatePom(portalSlug, moduleSlug, moduleLocators, urlBase, urlPath) {
  const className = pascal(moduleSlug) + 'Page';
  const mapKey    = moduleSlug; // matches locator-map.json top-level key
  const fullUrl   = urlBase + urlPath;

  const elementKeys = Object.keys(moduleLocators || {}).filter(k => k !== '_meta');

  const fieldLines = elementKeys.map(k => {
    const jsKey = safeJsKey(k);
    // Always bracket-access on L — keys may contain hyphens, start with digits, etc.
    const access = `L['${k.replace(/'/g, "\\'")}']`;
    return `    this.${jsKey.padEnd(30)} = page.locator(${access} && ${access}.selector);`;
  }).join('\n');

  const elementCount = elementKeys.length;

  return `'use strict';

/**
 * ${className}.js — Scaffolded Page Object Model for ${portalSlug} / ${moduleSlug}.
 *
 * AUTO-GENERATED by scripts/scaffold-poms.js — extend with business methods.
 * Selectors sourced from locators/${portalSlug}/locator-map.json (module key: "${mapKey}").
 *
 * Element count at scaffold time: ${elementCount}
 *
 * To enrich: add atomic action methods (e.g. submitForm, openModal, applyFilter)
 * following the BasePage helpers (click, fill, expectVisible, etc.).
 */

const { BasePage }   = require('../../base/BasePage');
const locatorMap     = require('../../../locators/${portalSlug}/locator-map.json');

const L = locatorMap['${mapKey}'] || {};

const ${pascal(moduleSlug).toUpperCase().replace(/[^A-Z_]/g, '_')}_URL = '${fullUrl}';

class ${className} extends BasePage {
  constructor(page) {
    super(page);
    this.L = L;
    this.url = ${pascal(moduleSlug).toUpperCase().replace(/[^A-Z_]/g, '_')}_URL;

    // ── Element locators (auto-generated from locator-map.json) ──────────────
${fieldLines || '    // (no elements in locator map yet — run crawler or add manually)'}
  }

  // ── Navigation ───────────────────────────────────────────────────────────

  async navigate() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForLoad() {
    await this.page.waitForLoadState('networkidle');
  }
}

module.exports = { ${className} };
`;
}

// ─── Orchestrator ────────────────────────────────────────────────────────────

function scaffoldPortal(portalSlug, opts = {}) {
  const cfg = PORTAL_FOLDER[portalSlug];
  if (!cfg) { console.log(`SKIP ${portalSlug} — unknown portal`); return; }

  const mapPath = path.join(LOCATORS, portalSlug, 'locator-map.json');
  if (!fs.existsSync(mapPath)) { console.log(`SKIP ${portalSlug} — no locator-map.json`); return; }
  let map;
  try { map = JSON.parse(fs.readFileSync(mapPath, 'utf8')); }
  catch (e) { console.log(`SKIP ${portalSlug} — locator-map.json unparseable`); return; }

  const pomDir = path.join(POM_BASE, cfg.pomDir);
  fs.mkdirSync(pomDir, { recursive: true });

  console.log(`\n=== ${portalSlug} ===`);
  let created = 0;
  let skipped = 0;
  const modules = MODULE_PATHS[portalSlug] || {};

  for (const [modSlug, modPath] of Object.entries(modules)) {
    const className = pascal(modSlug) + 'Page';
    const filePath  = path.join(pomDir, className + '.js');

    if (fs.existsSync(filePath) && !opts.force) {
      console.log(`  skip ${className.padEnd(30)} (exists)`);
      skipped++;
      continue;
    }

    const moduleLocators = map[modSlug] || {};
    const content = generatePom(portalSlug, modSlug, moduleLocators, cfg.urlBase, modPath);
    fs.writeFileSync(filePath, content);
    const keyCount = Object.keys(moduleLocators).length;
    console.log(`  ${opts.force && fs.existsSync(filePath) ? 'WRITE' : 'NEW '} ${className.padEnd(30)} (${keyCount} elements)`);
    created++;
  }

  console.log(`  ${portalSlug}: ${created} created, ${skipped} skipped`);
}

function main() {
  const args = process.argv.slice(2);
  const portalArg = args.find(a => a.startsWith('--portal='));
  const force = args.includes('--force');
  const only = portalArg ? portalArg.split('=')[1] : null;

  const targets = only ? [only] : Object.keys(PORTAL_FOLDER);
  for (const p of targets) scaffoldPortal(p, { force });
  console.log('\nDone.');
}

main();
