/**
 * ============================================================
 * AGENT 3 — AUTOMATION SCRIPT GENERATOR AGENT
 * ============================================================
 * Purpose : Convert approved manual test cases into Playwright
 *           automation scripts following Page Object Model.
 *
 * Inputs  : manual-test-cases/TC_<MODULE>.md
 *           docs/pages/<MODULE>.md
 *
 * Outputs : src/main/js/pages/<module>.page.js  (if not exists)
 *           src/test/automation/<module>.spec.js  (if not exists)
 *
 * Rules:
 *   - Each test must correspond to a Steps to Reproduce from TC
 *   - Never overwrite existing automation files
 *   - Use stable Playwright locators (no hardcoded waits)
 *   - Map each test to its TC_ID in comments
 *
 * Run:
 *   node src/test/agents/automation-agent.js <MODULE_NAME>
 *
 *   Example:
 *   node src/test/agents/automation-agent.js Customers
 * ============================================================
 */

const fs = require('fs');
const path = require('path');

const MODULE = process.argv[2];

const PAGES_DIR = path.join(process.cwd(), 'src', 'main', 'js', 'pages');
const TESTS_DIR = path.join(process.cwd(), 'src', 'test', 'automation');

function fileExists(filePath) {
  return fs.existsSync(filePath);
}

function generatePageObject(moduleName) {
  const fileName = `${moduleName.toLowerCase()}.page.js`;
  const filePath = path.join(PAGES_DIR, fileName);

  if (fileExists(filePath)) {
    console.log(`   ⚠️  Page Object already exists, skipping: ${filePath}`);
    console.log(`      (Agent 3 never overwrites existing files per GLOBAL_RULE_3)`);
    return;
  }

  const content = `/**
 * PAGE OBJECT — ${moduleName}
 * Generated by Agent 3 — Automation Script Generator
 *
 * ⚠️ DO NOT EDIT SELECTORS DIRECTLY.
 * If a selector breaks, use Agent 6 (Script Healing Agent) for recommendations.
 */
const { expect } = require('@playwright/test');
const { BasePage } = require('../base/BasePage.js');

class ${moduleName}Page extends BasePage {

  // ── Add your locators here based on docs/pages/${moduleName.toUpperCase()}.md ──

  constructor(page) {
    super(page);
  }

  async navigate() {
    await this.page.goto('https://uat-web.xrportal.in/admin/${moduleName.toLowerCase()}');
    console.log('✅ Navigated to ${moduleName} page');
  }

  async screenshot(label) {
    const ts = Date.now();
    await this.page.screenshot({ path: \`reports/screenshots/${moduleName.toLowerCase()}_\${label}_\${ts}.png\` });
  }
}

module.exports = { ${moduleName}Page };
`;
  fs.writeFileSync(filePath, content);
  console.log(`   ✅ Page Object created: ${filePath}`);
}

function generateSpecFile(moduleName) {
  const fileName = `${moduleName.toLowerCase()}.spec.js`;
  const filePath = path.join(TESTS_DIR, fileName);

  if (fileExists(filePath)) {
    console.log(`   ⚠️  Spec file already exists, skipping: ${filePath}`);
    console.log(`      (Agent 3 never overwrites existing files per GLOBAL_RULE_3)`);
    return;
  }

  const content = `/**
 * TEST SUITE — ${moduleName}
 * Generated by Agent 3 — Automation Script Generator
 *
 * Maps to: manual-test-cases/TC_${moduleName.toUpperCase()}.md
 * Page Object: src/main/js/pages/${moduleName.toLowerCase()}.page.js
 *
 * Run:
 *   npx playwright test --config resources/config/playwright.config.js ${moduleName.toLowerCase()}.spec.js --project=regression --headed --workers=1
 */

const { test, expect } = require('@playwright/test');
const { ${moduleName}Page } = require('../../main/js/pages/${moduleName.toLowerCase()}.page.js');
const path = require('path');

test.use({
  storageState: path.join(__dirname, '../fixtures/.auth/admin.json'),
});

test.describe('${moduleName} Module Tests', () => {

  test.beforeEach(async ({ page }) => {
    const module = new ${moduleName}Page(page);
    await module.navigate();
  });

  // ── Add test cases below, mapping each to its TC_ID ──────────────────

  // TODO: TC_${moduleName.toUpperCase()}_001 — Add first test case here

});
`;

  fs.writeFileSync(filePath, content);
  console.log(`   ✅ Spec file created: ${filePath}`);
}

function run() {
  console.log('⚙️  [Agent 3] AUTOMATION SCRIPT GENERATOR starting...\n');

  if (!MODULE) {
    console.log('Usage: node src/test/agents/automation-agent.js <ModuleName>');
    console.log('Example: node src/test/agents/automation-agent.js Towers');
    process.exit(1);
  }

  console.log(`📂 Generating automation for module: ${MODULE}`);
  generatePageObject(MODULE);
  generateSpecFile(MODULE);

  console.log(`\n✅ [Agent 3] AUTOMATION GENERATION COMPLETE for: ${MODULE}`);
  console.log(`   Next step → Update the generated files with real locators and test steps.`);
  console.log(`   Then run Agent 4 to execute tests.`);
}

run();
