/**
 * ============================================================
 * AGENT 6 — SCRIPT HEALING AGENT
 * ============================================================
 * Purpose : Analyze failed automation scripts and generate
 *           fix recommendations (does NOT auto-apply changes).
 *
 * Responsibilities:
 *   - Read Playwright test failure logs / traces
 *   - Detect selector failures, timing issues, UI changes
 *   - Output fix recommendations as markdown
 *
 * Outputs:
 *   healing-reports/script-failure-analysis.md
 *   healing-reports/fix-recommendations.md
 *
 * Rules:
 *   - Do NOT modify automation scripts automatically
 *   - Only provide structured recommendations
 *
 * Run:
 *   node src/test/agents/healing-agent.js
 * ============================================================
 */

const fs = require('fs');
const path = require('path');

const RESULTS_FILE    = path.join(process.cwd(), 'reports', 'results.json');
const HEALING_DIR     = path.join(process.cwd(), 'healing-reports');
const ANALYSIS_FILE   = path.join(HEALING_DIR, 'script-failure-analysis.md');
const FIX_FILE        = path.join(HEALING_DIR, 'fix-recommendations.md');

function detectFailureType(errorMessage) {
  const err = errorMessage.toLowerCase();

  if (err.includes('timeout') && err.includes('tobevisible')) {
    return {
      type: 'Selector Visibility Timeout',
      recommendation: `The element locator timed out. Possible causes:\n  1. The selector class/ID has changed in the UI.\n  2. The element loads after a dynamic API call.\n  Recommendation: Re-run Agent 0 (Discovery) to get the updated selector. Consider waiting for network idle before asserting.`,
    };
  }
  if (err.includes('strict mode violation')) {
    return {
      type: 'Multiple Elements Matched (Strict Mode Violation)',
      recommendation: `Multiple DOM elements matched the selector. The locator is not unique.\n  Recommendation: Add .first() to the locator, or scope the selector to a more specific parent container.`,
    };
  }
  if (err.includes('not attached')) {
    return {
      type: 'Element Detached from DOM',
      recommendation: `The element was found but then removed from the DOM mid-action. This is typically caused by a React/Vue re-render.\n  Recommendation: Add locator.waitFor({ state: 'visible' }) before interaction.`,
    };
  }
  if (err.includes('navigation')) {
    return {
      type: 'Navigation / URL Mismatch',
      recommendation: `The page did not navigate to the expected URL.\n  Recommendation: Check login credentials, session state, and network status. Re-run auth.setup.js.`,
    };
  }
  return {
    type: 'Unknown Failure',
    recommendation: `Review the trace file in test-results/ for step-by-step failure details.\n  Run: npx playwright show-report reports/html-report`,
  };
}

function run() {
  fs.mkdirSync(HEALING_DIR, { recursive: true });
  console.log('🩹 [Agent 6] SCRIPT HEALING AGENT starting...\n');

  if (!fs.existsSync(RESULTS_FILE)) {
    console.log('   ⚠️  No results.json found. Run Agent 4 first.');
    return;
  }

  const raw = JSON.parse(fs.readFileSync(RESULTS_FILE, 'utf-8'));
  const analyses = [];

  for (const suite of raw.suites || []) {
    for (const spec of suite.specs || []) {
      for (const test of spec.tests || []) {
        const result = test.results?.[0];
        if (result?.status !== 'failed') continue;

        const errorMessage = result.error?.message || '';
        const tcIdMatch = spec.title?.match(/TC_[A-Z_0-9]+/);
        const { type, recommendation } = detectFailureType(errorMessage);

        analyses.push({
          tcId: tcIdMatch ? tcIdMatch[0] : 'TC_UNKNOWN',
          testTitle: spec.title,
          errorMessage: errorMessage.slice(0, 300),
          failureType: type,
          recommendation,
          priority: type.includes('Selector') ? 'Immediate' : 'Next Sprint',
        });
      }
    }
  }

  if (analyses.length === 0) {
    console.log('   ✅ No failures to analyze. All scripts are healthy!');
    fs.writeFileSync(ANALYSIS_FILE, '# Script Failure Analysis\n\n✅ No failures detected.\n');
    fs.writeFileSync(FIX_FILE, '# Fix Recommendations\n\n✅ No fixes needed.\n');
    return;
  }

  // Write Analysis File
  let analysis = `# Script Failure Analysis\n\nGenerated by Agent 6 — Script Healing Agent\n\n---\n\n`;
  for (const a of analyses) {
    analysis += `## ${a.tcId} — ${a.testTitle}\n\n`;
    analysis += `| Field | Detail |\n| --- | --- |\n`;
    analysis += `| **Failure Type** | ${a.failureType} |\n`;
    analysis += `| **Priority** | ${a.priority} |\n`;
    analysis += `| **Error** | \`${a.errorMessage.replace(/\n/g, ' ')}\` |\n\n---\n\n`;
  }
  fs.writeFileSync(ANALYSIS_FILE, analysis);

  // Write Recommendations File
  let fixes = `# Fix Recommendations\n\nGenerated by Agent 6 — Script Healing Agent\n\n---\n\n`;
  for (const a of analyses) {
    fixes += `## ${a.tcId} — Fix Recommendation\n\n`;
    fixes += `**Priority:** ${a.priority}  \n`;
    fixes += `**Type:** ${a.failureType}  \n\n`;
    fixes += `${a.recommendation}\n\n---\n\n`;
    console.log(`   🩹 Analyzed: ${a.tcId} → ${a.failureType}`);
  }
  fs.writeFileSync(FIX_FILE, fixes);

  console.log(`\n✅ [Agent 6] HEALING ANALYSIS COMPLETE — ${analyses.length} issue(s) analyzed`);
  console.log(`   📄 Analysis: ${ANALYSIS_FILE}`);
  console.log(`   📄 Fixes: ${FIX_FILE}`);
}

run();
